$(document).ready(function(){
    $('#EB1').click(function(){
        $('#EB1').hide();
        $('#EB2').hide();
        $('#text1').show();
        $('#des1').show();
        $('#back1').show();
    });
    $('#back1').click(function(){
        $('#EB1').show();
        $('#EB2').show();
        $('#text1').hide();
        $('#des1').hide();
        $('#back1').hide();
    });
    $('#EB2').click(function(){
        $('#EB1').hide();
        $('#EB2').hide();
        $('#text2').show();
        $('#des2').show();
        $('#back2').show();
        $('#next1').show();
    });
    $('#back2').click(function(){
        $('#EB1').show();
        $('#EB2').show();
        $('#text2').hide();
        $('#des2').hide();
        $('#back2').hide();
        $('#next1').hide();
    });
    $('#next1').click(function(){
        $('#text2').hide();
        $('#des2').hide();
        $('#back2').hide();
        $('#next1').hide();
        $('.electrode').show();

        $('#text3').show();
        $('#des3').show();
        $('#back3').show();
        $('#next2').show();
    });
    $('#back3').click(function(){
        $('#text3').hide();
        $('#des3').hide();
        $('#back3').hide();
        $('#next2').hide();
        $('.electrode').hide();


        $('#text2').show();
        $('#des2').show();
        $('#back2').show();
        $('#next1').show();
    });
    $('#next2').click(function(){
        $('#text3').hide();
        $('#des3').hide();
        $('#back3').hide();
        $('#next2').hide();
        $('.electrode').hide();

        $('#text4').show();
        $('#des4').show();
        $('#back4').show();
        $('#next3').show();
        $('.electrodeholder').show();
    });
    $('#back4').click(function(){
        $('#text4').hide();
        $('#des4').hide();
        $('#back4').hide();
        $('#next3').hide();
        $('.electrodeholder').hide();

        $('#text3').show();
        $('#des3').show();
        $('#back3').show();
        $('#next2').show();
        $('.electrode').show();
    });
    $('#next3').click(function(){
        $('#text4').hide();
        $('#des4').hide();
        $('#back4').hide();
        $('#next3').hide();
        $('.electrodeholder').hide();
    
        $('#text5').show();
        $('#des5').show();
        $('#back5').show();
        $('#next4').show();
        $('.electrodecable').show();
    });
    $('#back5').click(function(){
        $('#text5').hide();
        $('#des5').hide();
        $('#back5').hide();
        $('#next4').hide();
        $('.electrodecable').hide();

        $('#text4').show();
        $('#des4').show();
        $('#back4').show();
        $('#next3').show();
        $('.electrodeholder').show();
    });
    $('#next4').click(function(){
        $('#text5').hide();
        $('#des5').hide();
        $('#back5').hide();
        $('#next4').hide();
        $('.electrodecable').hide();
    
        $('#text6').show();
        $('#des6').show();
        $('#back6').show();
        $('#next5').show();
        $('.metalp').show();
    });
    $('#back6').click(function(){
        $('#text6').hide();
        $('#des6').hide();
        $('#back6').hide();
        $('#next5').hide();
        $('.metalp').hide();

        $('#text5').show();
        $('#des5').show();
        $('#back5').show();
        $('#next4').show();
        $('.electrodecable').show();
    });
    $('#next5').click(function(){
        $('#text6').hide();
        $('#des6').hide();
        $('#back6').hide();
        $('#next5').hide();
        $('.metalp').hide();
    
        $('#text7').show();
        $('#des7').show();
        $('#back7').show();
        $('#next6').show();
        $('.setup').show();
    });
    $('#back7').click(function(){
        $('#text7').hide();
        $('#des7').hide();
        $('#back7').hide();
        $('#next6').hide();
        $('.setup').hide();

        $('#text6').show();
        $('#des6').show();
        $('#back6').show();
        $('#next5').show();
        $('.metalp').show();
    });
    $('#next6').click(function(){
    document.getElementById('b2').enabled;
    alert("Preprocessing is enabled!");
    $('#b2').click(function(){
        location.href="webpage_two.htm";
    });
    });
    document.getElementById('b2').disabled=true;
    document.getElementById('b3').disabled=true;
    document.getElementById('b4').disabled=true;
    $('#b5').click(function(){
    location.href="index.htm";
    });
    $('#b6').click(function(){
        $('#Ins').show();
    });
    $('.Cbtn').click(function(){
        $('#Ins').hide();
    });
});